from sofagym.envs.MultiGaitRobot.MultiGaitRobotEnv import *
from sofagym.envs.CartStemContact.CartStemContactEnv import *
from sofagym.envs.CartStem.CartStemEnv import *
from sofagym.envs.StemPendulum.StemPendulumEnv import *
from sofagym.envs.CatchTheObject.CatchTheObjectEnv import *
from sofagym.envs.BubbleMotion.BubbleMotionEnv import *
from sofagym.envs.Gripper.GripperEnv import *
from sofagym.envs.Trunk.TrunkEnv import *
from sofagym.envs.TrunkCup.TrunkCupEnv import *
from sofagym.envs.Diamond.DiamondEnv import *
from sofagym.envs.Maze.MazeEnv import *
from sofagym.envs.SimpleMaze.SimpleMazeEnv import *
from sofagym.envs.CTR.CTREnv import *
