from sofagym.envs.MultiGaitRobotEnv import *
from sofagym.envs.CartStemContactEnv import *
from sofagym.envs.CartStemEnv import *
from sofagym.envs.StemPendulumEnv import *
from sofagym.envs.CatchTheObjectEnv import *
from sofagym.envs.BubbleMotionEnv import *
from sofagym.envs.GripperEnv import *
from sofagym.envs.TrunkEnv import *
from sofagym.envs.TrunkCupEnv import *
from sofagym.envs.DiamondEnv import *
from sofagym.envs.MazeEnv import *
from sofagym.envs.SimpleMazeEnv import *
from sofagym.envs.CTREnv import *
