from sofagym.env.MultiGaitRobotEnv import *
from sofagym.env.CartStemContactEnv import *
from sofagym.env.CartStemEnv import *
from sofagym.env.StemPendulumEnv import *
from sofagym.env.CatchTheObjectEnv import *
from sofagym.env.BubbleMotionEnv import *
from sofagym.env.GripperEnv import *
from sofagym.env.TrunkEnv import *
from sofagym.env.TrunkCupEnv import *
from sofagym.env.DiamondEnv import *
from sofagym.env.MazeEnv import *
from sofagym.env.SimpleMazeEnv import *
from sofagym.env.CTREnv import *
